title: "실험 템플릿"
labels: "experiment, ongoing"

body:
  - type: markdown
    attributes:
      value: |
        ## 🧪 실험 템플릿
        아래 항목들을 채워주세요. 실험 설계와 진행 상황을 체계적으로 기록하는 데 도움을 줍니다.

  - type: input
    id: title
    attributes:
      label: 실험 제목
      description: 실험의 간단한 제목을 입력하세요.
      placeholder: "[Experiment] 모델 A vs 모델 B 비교 실험"
      required: true

  - type: textarea
    id: background
    attributes:
      label: 배경 (Background)
      description: 실험의 동기와 배경을 설명하세요.
      placeholder: |
        기존 모델의 성능 한계를 확인하기 위해 새로운 구조를 테스트합니다. 
        주요 목표는 RMSE를 5% 줄이는 것입니다.
      required: true

  - type: textarea
    id: hypothesis
    attributes:
      label: 가설 (Hypothesis)
      description: 이 실험의 가설을 작성하세요.
      placeholder: "모델 B는 모델 A보다 더 높은 예측 정확도를 가진다."
      required: true

  - type: textarea
    id: objective
    attributes:
      label: 실험 목표 (Objective)
      description: 실험으로 확인하고자 하는 내용을 구체적으로 명시하세요.
      placeholder: "두 모델의 성능을 비교하여 최적의 모델을 확인."
      required: true

  - type: textarea
    id: design
    attributes:
      label: 실험 설계 (Experiment Design)
      description: 데이터셋, 모델, 평가 지표 등을 포함한 실험 방법론을 설명하세요.
      placeholder: |
        - 데이터셋: MovieLens 1M
        - 모델:
          - 모델 A: Baseline
          - 모델 B: 새로운 구조
        - 평가 지표: RMSE, Precision@10
      required: true

  - type: textarea
    id: timeline
    attributes:
      label: 진행 계획 (Timeline)
      description: 실험 일정을 작성하세요.
      placeholder: |
        1주차: 데이터 전처리 및 모델 구성
        2주차: 모델 학습 및 평가
        3주차: 결과 분석 및 최종 보고
      required: true

  - type: textarea
    id: outcome
    attributes:
      label: 예상 결과 및 기준 (Expected Outcome and Criteria)
      description: 성공 기준과 예상되는 결과를 명시하세요.
      placeholder: |
        모델 B의 RMSE가 모델 A보다 5% 낮아야 성공으로 간주합니다.
      required: true

  - type: textarea
    id: references
    attributes:
      label: 참고 자료 (References)
      description: 관련 연구 논문, 문서, 또는 코드 링크를 추가하세요.
      placeholder: |
        - [논문 링크](https://example.com)
        - [코드 링크](https://github.com/example/repo)
      required: false

  - type: markdown
    attributes:
      value: |
        ### 참고 사항
        - 실험 결과와 진행 상황을 주기적으로 업데이트해주세요.
        - 주요 변경 사항은 팀과 공유해야 합니다.
